import Link from 'next/link'
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1776285047875-mvtv8fMkk7osjEWCypeWq12mH6xUoD.jpg'
const photos = {
  shuttle: ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/10%20Passenger%20E%20car%20for%20Africell%20Made%20by%20Sierra%20Electric.jfif-ZaMipho7TuDliZqhJp2H8U3QOYEpNi.jpeg', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260502-WA0077-5ezEdZC9FiA5rakFUTYGLc8j73stbx.jpg'],
  workshop: ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260503-WA0043-lyvB9V3ek7RLkUS4RGpam0jsk5iXDp.jpg', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1777656357345-Ken8nCRx0q1CGOaUECASxo92yO2MNg.jpg'],
  team: ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260502-WA0073-YXNqhvvPqrG6BHM1KVhKmlzAv94Kks.jpg', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1788633601074-tq50vfwHzaSJGLyUoihUUlugoDbn7d.jpg'],
}

type Project = { title: string; category: string; summary: string; challenge: string; solution: string; technology: string[]; status: string; impact: string; next: string; gallery?: string[] }
function galleryForSlug(slug: string) { if (slug === 'electric-shuttle' || slug === 'electric-mini-bus') return photos.shuttle; if (slug === 'first-electric-keke' || slug === 'automated-hand-washing-machine') return photos.workshop; return photos.team }
const projects: Record<string, Project> = {
  'electric-shuttle': { title: 'Electric Shuttle', category: 'Electric mobility · Built', summary: 'Sierra Leone’s first 100% electric shuttle minibus, developed around local engineering and practical transport needs.', challenge: 'Public transport must become cleaner, quieter and more affordable without losing the familiarity and usefulness of shared mobility.', solution: 'SET designed and built an electric shuttle platform, using local fabrication and engineering to explore accessible, locally maintainable transport.', technology: ['Electric drivetrain', 'Battery systems', 'Vehicle controls', 'Local fabrication'], status: 'Built / deployment details to confirm', impact: 'A working proof point for Sierra Leonean electric mobility and a platform for future public-transport partnerships.', next: 'Confirm passenger capacity, accessibility specification, deployment location, test data and operating results.' },
  'first-electric-keke': { title: 'First Electric Keke', category: 'Electric mobility · Conversion', summary: 'The first electric Keke built by SET, designed to carry passengers and accommodate people using wheelchairs.', challenge: 'Fuel-powered tricycles are familiar and widely used, but they create fuel costs, emissions and accessibility challenges.', solution: 'SET explored conversion rather than replacement: adapting a familiar Keke platform with an electric system and a more inclusive passenger layout.', technology: ['Electric motor', 'Battery and controller', 'Vehicle wiring', 'Accessible passenger space'], status: 'Built / full technical specification to confirm', impact: 'Demonstrates how existing transport platforms can become cleaner and more inclusive while supporting local maintenance skills.', next: 'Document range, payload, charging, wheelchair-access details, safety testing and commercialization pathway.' },
  'device-to-lamp': { title: 'Device-to-Lamp', category: 'Circular economy · Education', summary: 'A practical study-lamp concept made by repurposing old electronic devices and recovering useful components.', challenge: 'E-waste is growing while many learners still need reliable, low-cost study lighting.', solution: 'SET turns discarded electronics into useful lighting prototypes, combining repair, reuse and hands-on technical learning.', technology: ['Recovered electronics', 'LED lighting', 'Battery integration', 'Product prototyping'], status: 'Prototype / results to confirm', impact: 'Connects circular economy practice with education, technical skills and a lower-cost approach to study lighting.', next: 'Confirm prototype count, power source, users, test results and pathway for community deployment.' },
  'solar-backpack': { title: 'Solar Backpack', category: 'Clean energy · Education', summary: 'A solar-generating backpack concept that supports study lighting and device charging.', challenge: 'Learners need portable, resilient access to light and device power.', solution: 'SET explores integrating solar generation and storage into a practical everyday backpack.', technology: ['Solar generation', 'Portable storage', 'LED study light', 'Device charging'], status: 'Pilot / details to confirm', impact: 'Connects clean energy access with education and mobility.', next: 'Confirm power output, battery capacity, prototype testing and users.' },
  'smart-farm': { title: 'Smart Farm', category: 'Smart agriculture · Demonstration site', summary: 'A living site for solar-powered irrigation, weather monitoring, composting and crop-health research.', challenge: 'Climate resilience requires farms to use water, energy and data more efficiently.', solution: 'SET brings clean energy, monitoring and practical farm systems together in a demonstration environment.', technology: ['Solar irrigation', 'Weather monitoring', 'Composting', 'Crop-health research'], status: 'Demonstration site / details to confirm', impact: 'Shows how climate technology can support food systems and practical learning.', next: 'Confirm site, crops, partners, monitoring data and results.' },
  'electric-mini-bus': { title: 'Electric Mini Bus', category: 'Electric mobility · Public transport', summary: 'A larger-scale electric public-transport direction building on SET’s shuttle and vehicle engineering work.', challenge: 'Cities need public transport that reduces fuel dependence and emissions while remaining practical for everyday passengers.', solution: 'SET is developing knowledge across vehicle conversion, battery systems, accessibility and local fabrication to support future electric mini-bus deployment.', technology: ['Electric drivetrain', 'Battery management', 'Charging systems', 'Vehicle fabrication'], status: 'Development direction / project details to confirm', impact: 'Creates a pathway from a working electric shuttle toward scalable, locally supported public transport.', next: 'Confirm whether this is a distinct vehicle, its build stage, capacity, route and deployment partners.' },
  'automated-hand-washing-machine': { title: 'Automated Hand-Washing Machine', category: 'Engineering · Public health', summary: 'An automated hand-washing concept designed to make hygiene safer, more consistent and easier to access.', challenge: 'Public hand-washing requires reliable water delivery while reducing touch points and encouraging consistent use.', solution: 'SET applies local prototyping and simple automation to create a practical, maintainable hand-washing solution.', technology: ['Sensors or controls', 'Water delivery', 'Local fabrication', 'User-centered design'], status: 'Prototype / technical details to confirm', impact: 'Shows how SET’s workshop can respond to practical community needs beyond mobility and energy.', next: 'Confirm activation method, power source, deployment site, water capacity and test outcomes.' },
  'greenshift-systems': { title: 'GreenShift Systems', category: 'Climate innovation · Integrated systems', summary: 'An integrated model connecting solar charging, electric mobility and climate-smart agriculture.', challenge: 'Climate solutions are strongest when transport, energy, food systems and youth opportunity are designed together.', solution: 'GreenShift links practical climate technologies with innovation training, community projects and pathways to green employment.', technology: ['Solar energy', 'Electric mobility', 'Smart agriculture', 'Climate innovation'], status: 'Flagship blueprint / programme details to confirm', impact: 'Provides a systems-level framework for youth-led climate action and locally relevant green technology.', next: 'Confirm participating communities, delivered projects, partners, results and future programme plans.' },
}

export function generateStaticParams() { return Object.keys(projects).map((slug) => ({ slug })) }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const project = projects[slug] ?? projects['electric-shuttle']
  const gallery = project.gallery ?? galleryForSlug(slug)
  return <main className="project-detail-page"><header className="site-header"><Link className="brand" href="/"><img className="brand-logo" src={logo} alt="Sierra Electric Technologies logo" /><span>SIERRA ELECTRIC<br /><b>TECHNOLOGIES</b></span></Link><Link className="pill-button outline" href="/#projects"><ArrowLeft size={15} /> Back to projects</Link></header><section className="project-detail-hero section-pad"><span className="eyebrow"><span className="eyebrow-dot" /> Project case study</span><p className="project-detail-category">{project.category}</p><h1>{project.title}</h1><p className="project-detail-summary">{project.summary}</p><span className="status-pill"><span className="status-dot" />{project.status}</span></section><section className="project-gallery section-pad"><div><span className="kicker">Project views</span><h2>See the work from <em>every angle.</em></h2></div><div className="project-gallery-grid">{gallery.map((image, index) => <img key={image} src={image} alt={`${project.title} project view ${index + 1}`} />)}</div></section><section className="project-detail-body section-pad"><div className="project-detail-intro"><span className="kicker">Inside the work</span><h2>From challenge to <em>practical solution.</em></h2></div><div className="project-detail-copy"><article><span className="kicker">The challenge</span><p>{project.challenge}</p></article><article><span className="kicker">The solution</span><p>{project.solution}</p></article><article><span className="kicker">Impact</span><p>{project.impact}</p></article><article><span className="kicker">What comes next</span><p>{project.next}</p></article></div></section><section className="project-tech-section section-pad"><div><span className="kicker light-kicker">Technology and build</span><h2>Built with local <em>purpose.</em></h2></div><div className="project-tech-list">{project.technology.map((item) => <div key={item}><CheckCircle2 size={18} /><span>{item}</span></div>)}</div></section><section className="project-detail-cta section-pad"><span className="kicker">Need the complete project file?</span><h2>Ask SET for the <em>technical record.</em></h2><p>Some project specifications, dates, partners, measurements and photographs are still marked for confirmation. Contact SET for the verified project information as it becomes available.</p><Link className="pill-button primary" href="/#contact">Request project information <ArrowRight size={15} /></Link></section></main>
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects[slug] ?? projects['electric-shuttle']; return { title: `${project.title} | Sierra Electric Technologies`, description: project.summary } }
