import Link from 'next/link'
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1776285047875-mvtv8fMkk7osjEWCypeWq12mH6xUoD.jpg'
const services = {
  'electric-mobility': { title: 'Electric mobility', summary: 'Electric bikes, tricycles and shuttle systems adapted for Sierra Leonean realities.', details: ['Vehicle conversion and locally relevant electric transport prototypes.', 'Battery, drivetrain, charging and accessibility questions considered together.', 'Current service scope, fleet options and deployment partnerships require confirmation.'] },
  'clean-energy': { title: 'Clean energy', summary: 'Solar systems, storage and energy access solutions designed for resilience.', details: ['Practical solar generation and storage concepts for homes, learning and enterprise.', 'Energy systems designed around reliability, maintainability and local context.', 'Available products, installation services and performance data require confirmation.'] },
  'smart-agriculture': { title: 'Smart agriculture', summary: 'Irrigation, monitoring and EV-supported farm logistics for climate resilience.', details: ['Solar-powered irrigation, weather monitoring and crop-health research.', 'Electric mobility supports the movement of people, tools and farm outputs.', 'Demonstration sites, crops, partners and measured outcomes require confirmation.'] },
  'climate-innovation': { title: 'Climate innovation', summary: 'Youth-led circular economy, climate entrepreneurship and community solutions.', details: ['Young builders turn local challenges into prototypes, enterprises and learning.', 'Circular design connects e-waste recovery, skills and useful products.', 'Cohorts, partnerships and current opportunities require confirmation.'] },
} as const

export function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })) }
export default async function WorkPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug as keyof typeof services] ?? services['electric-mobility']; return <main className="project-detail-page"><header className="site-header"><Link className="brand" href="/"><img className="brand-logo" src={logo} alt="Sierra Electric Technologies logo" /><span>SIERRA ELECTRIC<br /><b>TECHNOLOGIES</b></span></Link><Link className="pill-button outline" href="/#work"><ArrowLeft size={15} /> Back to what we do</Link></header><section className="project-detail-hero section-pad"><span className="eyebrow"><span className="eyebrow-dot" /> SET capability</span><h1>{service.title}</h1><p className="project-detail-summary">{service.summary}</p></section><section className="project-detail-body section-pad"><div className="project-detail-intro"><span className="kicker">Our approach</span><h2>Technology made for <em>real-world impact.</em></h2></div><div className="project-detail-copy">{service.details.map((detail) => <article key={detail}><CheckCircle2 size={18} /><p>{detail}</p></article>)}</div></section><section className="project-detail-cta section-pad"><span className="kicker">Start a conversation</span><h2>Build the next <em>practical solution.</em></h2><p>Contact SET for a verified capability brief, project references and partnership options.</p><Link className="pill-button primary" href="/#contact">Talk to SET <ArrowRight size={16} /></Link></section></main> }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug as keyof typeof services] ?? services['electric-mobility']; return { title: `${service.title} | Sierra Electric Technologies`, description: service.summary } }
