import Link from 'next/link'
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1776285047875-mvtv8fMkk7osjEWCypeWq12mH6xUoD.jpg'
const services = {
  'electric-mobility': { title: 'Electric mobility', summary: 'Electric bikes, tricycles and shuttle systems adapted for Sierra Leonean realities.', details: ['SET explores practical electric transport across bikes, tricycles, shuttles, mini-buses and farm vehicles.', 'The work connects local fabrication, battery systems, drivetrain design, charging, accessibility and maintainability.', 'The first electric Keke is designed to carry passengers, including wheelchair users, while the SET / EV-01 shuttle demonstrates locally built electric transport.', 'Future work includes electric mini-bus development, fleet partnerships, charging infrastructure and field validation.'], focus: ['Vehicle conversion and prototype engineering', 'Wheelchair-accessible passenger mobility', 'Electric shuttle and mini-bus systems', 'Locally serviceable charging and battery systems'] },
  'clean-energy': { title: 'Clean energy', summary: 'Solar systems, storage and energy access solutions designed for resilience.', details: ['SET develops clean-energy concepts that connect solar generation, storage, lighting and productive use.', 'The Sierra Circular Energy Initiative repurposes usable battery cells from mobile devices and small solar systems into affordable backpacks, lighting kits and charging units.', 'Solar-powered school backpacks, created with Wanjama Innovative Salone since 2021, support study lighting and device charging in off-grid communities.', 'The approach prioritizes safety, repairability, local skills and reliable energy access for households, schools and small businesses.'], focus: ['Solar generation and storage', 'Battery recovery and safe testing', 'Solar school backpacks', 'Portable lighting and charging'] },
  'smart-agriculture': { title: 'Smart agriculture', summary: 'Irrigation, monitoring and EV-supported farm logistics for climate resilience.', details: ['SET combines solar-powered irrigation, weather monitoring, composting and crop-health research in practical demonstration environments.', 'The Electric Farm Vehicle SEFT-V is a four-wheel electric farm cart designed for produce, tools and people across rural terrain.', 'The validated concept targets approximately 500 kilograms of load capacity, a 72-volt lithium-ion battery, an axle-driven motor and assistive solar charging.', 'The design emphasizes local manufacturing, simple maintenance and lower dependence on fuel for smallholder farmers.'], focus: ['Solar irrigation and water resilience', 'Weather and crop monitoring', 'Electric farm logistics', 'Local manufacturing and maintenance'] },
  'climate-innovation': { title: 'Climate innovation', summary: 'Youth-led circular economy, climate entrepreneurship and community solutions.', details: ['SET gives young builders a pathway from local problem identification to prototype, enterprise and deployment.', 'The Sierra Circular Energy Initiative creates roles for youth collectors and technicians in e-waste recovery, battery testing and solar product assembly.', 'Climate innovation spans electric mobility, clean energy, agriculture, circular design and community-based enterprise.', 'The work is designed to grow through partnerships, training, local production and evidence from field pilots.'], focus: ['Youth technical training and employment', 'Circular economy and e-waste recovery', 'Climate entrepreneurship', 'Community-led prototypes and partnerships'] },
} as const

export function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })) }
export default async function WorkPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug as keyof typeof services] ?? services['electric-mobility']; return <main className="project-detail-page"><header className="site-header"><Link className="brand" href="/"><img className="brand-logo" src={logo} alt="Sierra Electric Technologies logo" /><span>SIERRA ELECTRIC<br /><b>TECHNOLOGIES</b></span></Link><Link className="pill-button outline" href="/#work"><ArrowLeft size={15} /> Back to what we do</Link></header><section className="project-detail-hero section-pad"><span className="eyebrow"><span className="eyebrow-dot" /> SET capability</span><h1>{service.title}</h1><p className="project-detail-summary">{service.summary}</p></section><section className="project-detail-body section-pad"><div className="project-detail-intro"><span className="kicker">Our approach</span><h2>Technology made for <em>real-world impact.</em></h2></div><div className="project-detail-copy">{service.details.map((detail) => <article key={detail}><CheckCircle2 size={18} /><p>{detail}</p></article>)}<div className="capability-focus"><span className="kicker">What this includes</span>{service.focus.map((item) => <div className="focus-item" key={item}><CheckCircle2 size={16} /> <span>{item}</span></div>)}</div></div></section><section className="project-detail-cta section-pad"><span className="kicker">Start a conversation</span><h2>Build the next <em>practical solution.</em></h2><p>Contact SET for a verified capability brief, project references and partnership options.</p><Link className="pill-button primary" href="/#contact">Talk to SET <ArrowRight size={16} /></Link></section></main> }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug as keyof typeof services] ?? services['electric-mobility']; return { title: `${service.title} | Sierra Electric Technologies`, description: service.summary } }
