'use client'

import { useState } from 'react'
import { ArrowRight, Check, Globe2, Mail, MapPin, Menu, MoveUpRight, Phone, X } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1776285047875-mvtv8fMkk7osjEWCypeWq12mH6xUoD.jpg'
const shuttle = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/10%20Passenger%20E%20car%20for%20Africell%20Made%20by%20Sierra%20Electric.jfif-ZaMipho7TuDliZqhJp2H8U3QOYEpNi.jpeg'
const workshop = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260811-WA0016-Yig3FYAvJI3CxTFC47olxk8ZZVTkaZ.jpg'
const engineer = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1786993801626-l1z3FnX2M1ZM9KAvn4rafgclZAFQ7g.jpg'
const blackVehicle = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/0f360a7e-ec58-4bb6-9d73-f39bc5d453df%20%281%29.jfif-xN5PgLAjYsfbRMkXdFvidbMRQpcTDR.jpeg'
const specialGuest = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1777063666742-Kd3R5Bczi6WMSLVb8JCZHOqiWD8NsJ.jpg'
const youngBuilder = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_20260703_042354_068-NXAEgW5Ng0MzHdxAyGB27dLbaz7mGe.jpg'
const guestPortrait = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1777063666742-Kd3R5Bczi6WMSLVb8JCZHOqiWD8NsJ.jpg'
const trainingRoom = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1777656357345-Ken8nCRx0q1CGOaUECASxo92yO2MNg.jpg'
const panel = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1788633531253-c3uenFU6ChUVvBRDVkEfrI0CSDUbTW.jpg'
const workshopTeam = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260502-WA0077-5ezEdZC9FiA5rakFUTYGLc8j73stbx.jpg'
const recognition = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260502-WA0073-YXNqhvvPqrG6BHM1KVhKmlzAv94Kks.jpg'
const greenshiftGroup = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1788633601074-tq50vfwHzaSJGLyUoihUUlugoDbn7d.jpg'

const nav = [
  ['About', '#about'], ['What we do', '#work'], ['Projects', '#projects'],
  ['Programmes', '#programmes'], ['People', '#people'], ['Contact', '#contact'],
]
const work = [
  ['01', 'Electric mobility', 'Electric bikes, tricycles and shuttle systems adapted for Sierra Leonean realities.'],
  ['02', 'Clean energy', 'Solar systems, storage and energy access solutions designed for resilience.'],
  ['03', 'Smart agriculture', 'Irrigation, monitoring and EV-supported farm logistics for climate resilience.'],
  ['04', 'Climate innovation', 'Youth-led circular economy, climate entrepreneurship and community solutions.'],
]
const projects = [
  ['Electric Shuttle', 'Built / mobility', 'Sierra Leone’s first 100% electric shuttle minibus, with accessibility considerations and 75% locally sourced materials.', shuttle],
  ['Electric Keke Conversion', 'In development / mobility', 'Exploring how familiar fuel-powered tricycles can become lower-cost electric transport platforms.', blackVehicle],
  ['Solar Backpack', 'Pilot / energy + education', 'A solar-generating backpack concept that supports study lighting and device charging.', workshop],
  ['Device-to-Lamp', 'Circular economy', 'Repurposing old electronic devices into practical study lamps while reducing e-waste.', engineer],
  ['GreenShift Systems', 'Flagship blueprint', 'An integrated model connecting solar charging, electric mobility and climate-smart agriculture.', workshop],
  ['Smart Farm', 'Demonstration site', 'A living site for solar-powered irrigation, weather monitoring, composting and crop-health research.', workshop],
]
const faqs = [
  ['What is Sierra Electric Technologies?', 'SET SL is a youth-led Sierra Leonean technology and engineering company developing practical solutions across electric mobility, clean energy, sustainable agriculture and climate innovation.'],
  ['Does SET build electric vehicles?', 'Yes. SET built Sierra Leone’s first 100% electric shuttle minibus and continues to develop and test electric mobility and conversion concepts.'],
  ['Can organizations partner with SET?', 'Yes. We welcome conversations with government, funders, NGOs, universities, businesses, technology companies and research partners.'],
  ['Does SET offer training?', 'SET develops technical skills and green-employment pathways. Programme availability and application windows should be confirmed directly with the team.'],
  ['How can I contact SET?', 'Email sierraelectric.sl@gmail.com, call +232 80 247163, or use the Facebook page linked below.'],
]

function Mark({ light = false }: { light?: boolean }) { return <img className={`brand-logo ${light ? 'brand-logo-light' : ''}`} src={logo} alt="Sierra Electric Technologies logo" /> }
function Button({ children, href = '#', outline = false }: { children: React.ReactNode; href?: string; outline?: boolean }) { return <a className={`pill-button ${outline ? 'outline' : 'primary'}`} href={href}>{children}<ArrowRight size={16} /></a> }
function SectionTitle({ kicker, title, children }: { kicker: string; title: React.ReactNode; children?: React.ReactNode }) { return <div className="section-heading-row"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div>{children}</div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Sierra Electric Technologies home"><Mark /><span>SIERRA ELECTRIC<br /><b>TECHNOLOGIES</b></span></a><nav id="mobile-navigation" className={`desktop-nav ${menuOpen ? 'is-open' : ''}`} aria-label="Main navigation">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<Button href="#contact">Partner with us</Button></nav><div className="header-actions"><button className="language" aria-label="Language"><Globe2 size={18} /> EN</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></div></header>

    <section className="hero section-pad" id="top"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot" /> Youth-led climate technology</span><h1>Engineering a <em>cleaner, smarter</em> future.</h1><p className="hero-sub">Sierra Electric Technologies builds practical clean-energy, electric-mobility, agricultural and climate solutions for Sierra Leone and Africa.</p><div className="hero-actions"><Button href="#projects">Explore our work</Button><Button href="#about" outline>Discover SET</Button></div><a className="text-link" href="#contact">Let&apos;s build what comes next <MoveUpRight size={15} /></a></div><div className="hero-visual hero-photo"><img className="hero-photo-image" src={shuttle} alt="A SET electric shuttle inside the workshop" /><div className="hero-photo-overlay" /><div className="visual-label label-top">SET / EV-01 <span>built in Sierra Leone</span></div><div className="visual-label label-bottom"><span className="green-line" /> First electric vehicle built in Sierra Leone</div></div></section>

    <section className="capabilities section-pad" id="work"><div className="section-intro"><span className="kicker">What SET does</span><h2>Technology made for <em>real-world impact.</em></h2><p>Our systems-thinking approach connects energy, mobility, agriculture, engineering and people — moving from problem to prototype to deployment.</p></div><div className="capability-grid">{work.map(([number, title, text]) => <article className="capability-card" key={title}><div className="icon-chip"><span>{number}</span></div><h3>{title}</h3><p>{text}</p><a className="card-link" href="#projects">Explore <ArrowRight size={15} /></a></article>)}</div></section>

    <section className="dark-section section-pad" id="about"><div className="dark-grid"><div><span className="kicker light-kicker">Who we are</span><h2>Local problems deserve <em>local engineering.</em></h2></div><div><p className="dark-lead">Incorporated on 29 July 2023, SET SL is a youth-led climate-tech social enterprise headquartered in Freetown. We are building a scalable African platform at the intersection of energy, transport, food systems and green employment.</p><ul className="check-list"><li><Check size={16} /> 75% locally sourced shuttle build</li><li><Check size={16} /> 2024 National Innovation Challenge winner</li><li><Check size={16} /> 2025 MOCTI Young Innovator of the Year recognition</li></ul><Button href="#contact">Partner with SET</Button></div></div></section>

    <section className="feature-strip section-pad"><span>Problem</span><i /><span>Research</span><i /><span>Prototype</span><i /><span>Testing</span><i /><span>Deployment</span><i /><span>Impact</span></section>

    <section className="projects-section section-pad" id="projects"><SectionTitle kicker="Complete project portfolio" title={<>Proof in <em>progress.</em></>}><a className="text-link" href="#contact">Request project details <ArrowRight size={15} /></a></SectionTitle><div className="project-browser"><div className="browser-bar"><span /><span /><span /><p>set.sl / projects / electric-shuttle</p><span className="browser-code">01 — 06</span></div><div className="project-feature"><div className="project-feature-copy"><span className="status-pill"><span /> Built / verified</span><h3>Electric<br /><em>Shuttle</em></h3><p>Sierra Leone’s first 100% electric shuttle minibus, designed and built locally with a wheelchair ramp and accessibility in mind.</p><div className="project-meta"><span>Electric mobility</span><span>Freetown, Sierra Leone</span></div><a href="#contact" className="card-link">Request the case study <ArrowRight size={15} /></a></div><div className="project-visual project-real-photo"><img src={shuttle} alt="Pink 10-passenger electric vehicle built by Sierra Electric Technologies" /></div></div></div><div className="project-cards">{projects.slice(1).map(([title, tag, text, image]) => <article className="project-card" key={title}><div className="project-thumb"><img src={image} alt={`${title} project at Sierra Electric Technologies`} /><span className="status-pill">{tag}</span></div><div className="project-card-copy"><span className="kicker">{title}</span><p>{text}</p><a className="card-link" href="#contact">Project information <ArrowRight size={15} /></a></div></article>)}</div></section>

    <section className="people-section section-pad" id="people"><SectionTitle kicker="People and leadership" title={<>Young people, <em>serious builders.</em></>}><p className="people-intro">SET is powered by young engineers, operators, programme builders and collaborators. Confirmed public profiles are shown below; additional names and biographies are marked for confirmation.</p></SectionTitle><div className="people-grid"><article className="person-card person-feature"><div className="person-photo"><img src={engineer} alt="James Samba, founder of Sierra Electric Technologies, in engineering safety gear" /></div><div className="person-copy"><span className="kicker">Founder &amp; CEO</span><h3>James Samba</h3><p>Founder, technology builder and 2025 MOCTI Young Innovator of the Year. His journey from experimenting with discarded electronics to electric mobility anchors SET&apos;s culture of curiosity and practical engineering.</p></div></article><article className="person-card"><div className="person-photo"><img src={youngBuilder} alt="Samuel Samura, Administrative Officer and Software Engineer at Sierra Electric Technologies" /></div><div className="person-copy"><span className="kicker">Administrative Officer &amp; Software Engineer</span><h3>Samuel Samura</h3><p>A relentless Sierra Leonean builder and problem-solver working across engineering, technology, startups and leadership. Samuel helps turn ambitious ideas into practical systems while studying at Fourah Bay College.</p></div></article><article className="person-card"><div className="person-photo"><img src={shuttle} alt="SET engineering team workspace and electric vehicle" /></div><div className="person-copy"><span className="kicker">Engineering team</span><h3>Builders in the workshop</h3><p>Information required: confirm chief engineer, engineers, operations team, programme team, advisors and mentors.</p></div></article><article className="person-card"><div className="person-photo person-photo-placeholder"><span>Profile photo<br />to be supplied</span></div><div className="person-copy"><span className="kicker">Co-Founder</span><h3>Leadership profile</h3><p>Information required: confirm the co-founder&apos;s name, biography, responsibilities and public profile.</p></div></article></div><div className="workspace-strip"><div><span className="kicker">Our workspace</span><h3>The workshop is where ideas become <em>working solutions.</em></h3><p>Visitors, partners and collaborators meet the team around vehicles, wiring, fabrication and experiments — not just presentations.</p></div><div className="workspace-images"><img src={workshop} alt="SET workshop interior" /><img src={blackVehicle} alt="SET electric vehicle outside a partner location" /><img src={engineer} alt="SET engineer in safety equipment" /></div></div></section>

    <section className="media-journal section-pad" id="media"><SectionTitle kicker="Stories from the field" title={<>SET in motion, <em>in the room.</em></>}><a className="text-link" href="#contact">Share a story <ArrowRight size={15} /></a></SectionTitle><div className="media-grid"><article className="media-card media-card-large"><img src={specialGuest} alt="A special guest visits the Sierra Electric Technologies workshop and meets the team" /><div><span className="kicker">A visit from Pontus Edenberg</span><p>Pontus Edenberg, CEO of Swedish technology company Twingly, visited SET&apos;s workshop to meet the team and see locally built electric-mobility work up close. Twingly provides API-based media intelligence data across news, blogs, forums and reviews; his visit reflects the value of connecting Sierra Leonean builders with international technology leaders.</p></div></article><article className="media-card"><img src={greenshiftGroup} alt="GreenShift participants celebrating together in 2025" /><div><span className="kicker">GreenShift</span><p>Youth climate innovators gathering, learning and building community.</p></div></article><article className="media-card"><img src={trainingRoom} alt="SET team members and trainees working together in a training room" /><div><span className="kicker">Training in the room</span><p>Practical learning, technical confidence and collaboration.</p></div></article><article className="media-card"><img src={workshopTeam} alt="SET team working around electric vehicle components in the workshop" /><div><span className="kicker">Workshop at Freetown Innovation Lab</span><p>Engineering teams examine batteries, wiring and mobility systems.</p></div></article><article className="media-card"><img src={panel} alt="SET team members speaking on a public panel" /><div><span className="kicker">On television and in public</span><p>SET&apos;s climate and technology work reaches wider conversations.</p></div></article><article className="media-card"><img src={recognition} alt="SET team members holding a STEM Africa Fest certificate of recognition" /><div><span className="kicker">Recognition and milestones</span><p>Team achievements that document SET&apos;s growing ecosystem.</p></div></article></div></section>

  <section className="programmes section-pad" id="programmes"><div className="programme-copy"><span className="kicker">Programmes and skills</span><h2>Building the skills behind a <em>greener future.</em></h2><p>GreenShift develops youth climate innovation. FORGE creates practical pathways for women into welding, fabrication, EV wiring and green employment.</p><Button href="#contact">Discuss a programme</Button></div><div className="programme-stack"><div className="programme-card forge"><span className="programme-number">01</span><span className="status-pill">Status to confirm</span><h3>FORGE</h3><p>Fabrication, Operations and Roads to Green Employment. Six-week women-focused technical training concept.</p></div><div className="programme-card greenshift"><span className="programme-number">02</span><span className="status-pill">SET-associated initiative</span><h3>GreenShift</h3><p>Youth climate innovation across mobility, clean energy, agriculture and community solutions.</p></div></div></section>

    <section className="impact-section section-pad" id="impact"><div className="section-intro"><span className="kicker">Impact and recognition</span><h2>Proof, not <em>promises.</em></h2><p>We distinguish verified achievements from pilots, concepts and future plans. Impact reporting will expand as SET confirms project data.</p></div><div className="stats-grid"><div><b>01</b><span>First 100% electric vehicle built in Sierra Leone</span></div><div><b>75%</b><span>Locally sourced materials reported for the shuttle build</span></div><div><b>2024</b><span>National Innovation Challenge winner</span></div><div><b>2025</b><span>MOCTI Young Innovator of the Year recognition</span></div><div><b>Info</b><span>CO₂, jobs, trainees, beneficiaries and deployment data required for confirmation</span></div><div><b>SDGs</b><span>Aligned with SDGs 2, 7, 8, 11 and 13 and Africa Agenda 2063</span></div></div></section>

    <section className="directory-section section-pad" id="directory"><SectionTitle kicker="Everything a partner needs" title={<>A transparent <em>institutional profile.</em></>} /><div className="directory-grid">{[['Research & development', 'EV systems, batteries, solar, agriculture technology, sensors, IoT, AI and embedded systems.'], ['Customers & services', 'Current commercial products, fabrication, engineering, energy, training and consulting scope requires confirmation.'], ['Partnerships', 'Government, universities, NGOs, development partners, funders, private sector and research collaborators.'], ['Careers', 'Technical roles, internships, apprenticeships, volunteers and programme opportunities — availability requires confirmation.'], ['Future roadmap', 'Local expansion, GreenShift pilots, manufacturing, training, regional replication and new climate technologies.'], ['Media & press', 'Awards, interviews, photos, videos, press releases and downloadable press kit require confirmation and curation.']].map(([title, text]) => <article className="directory-card" key={title}><h3>{title}</h3><p>{text}</p><span className="status-pill">Information / status to confirm</span></article>)}</div></section>

    <section className="faq-section section-pad" id="faq"><SectionTitle kicker="Frequently asked questions" title={<>Start with the <em>facts.</em></>} /><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="contact-section section-pad" id="contact"><div><span className="kicker light-kicker">Contact and locations</span><h2>Let&apos;s build what <em>comes next.</em></h2></div><div><p>For partnership, investment, media, training, careers, project enquiries or general questions, contact the SET team directly.</p><div className="contact-actions" aria-label="SET contact options"><a className="contact-icon" href="mailto:sierraelectric.sl@gmail.com" aria-label="Email Sierra Electric Technologies" title="Email Sierra Electric Technologies"><Mail size={22} /></a><a className="contact-icon" href="tel:+23280247163" aria-label="Call Sierra Electric Technologies" title="Call Sierra Electric Technologies"><Phone size={22} /></a><a className="contact-icon" href="https://maps.google.com/?q=1+Sesay+Drive+off+Fadika+Drive+Imatt+Freetown+Sierra+Leone" target="_blank" rel="noreferrer" aria-label="Open SET location in Google Maps" title="Open location in Google Maps"><MapPin size={22} /></a><a className="contact-icon contact-facebook" href="https://www.facebook.com/sierraelectricsl" target="_blank" rel="noreferrer" aria-label="Visit Sierra Electric Technologies on Facebook" title="Visit SET on Facebook">f</a></div></div></section>

    <footer className="site-footer"><div className="footer-main"><a className="brand brand-footer" href="#top"><Mark light /><span>SIERRA ELECTRIC<br /><b>TECHNOLOGIES</b></span></a><p>A Sierra Leonean technology and engineering company building practical solutions for a cleaner, smarter future.</p><div className="socials"><a href="https://www.facebook.com/sierraelectricsl" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a href="mailto:sierraelectric.sl@gmail.com" aria-label="Email">@</a></div></div><div className="footer-links"><div><span>Explore</span><a href="#about">About SET</a><a href="#work">What we do</a><a href="#projects">Projects</a><a href="#people">People</a></div><div><span>Connect</span><a href="#programmes">Programmes</a><a href="#faq">FAQ</a><a href="#contact">Partner with us</a><a href="mailto:sierraelectric.sl@gmail.com">Contact</a></div></div><div className="footer-bottom"><span>© 2026 Sierra Electric Technologies SL</span><span>Freetown, Sierra Leone <span className="footer-dot" /> Built for Africa</span></div></footer>
  </main>
}
